
title: <p align="center"> Suresh Patil </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/sureshpatil777">GitHub</a>
  
  <br>   
  I am pursuing Master's Degree in Machine Learning & AI 
  from Liverpool John Moores University, UK
  <br>
  </p>



theme: jekyll-theme-minimal
